glib: Autospec creation for update from version 2.52.1 to version 2.52.2
Overview of changes in GLib 2.52.2
==================================

* Bug fixes:
 734946 Implement GContentType on OSX
 761102 Increase performance for main loop
 780300 gio/gosxappinfo.c uses deprecated LSFindApplicationForInfo
 780309 gio/tests/appinfo build fails: gdesktopappinfo.c skipped on OS X
 781298 gfileutils.c:330:3: error: ISO C90 forbids mixed declarations and code

* Translation updates:
 Indonesian

    2.52.2

 NEWS         | 14 ++++++++++++++
 configure.ac |  4 ++--
 2 files changed, 16 insertions(+), 2 deletions(-)

commit 3a6811a46084474e2308bdc991645f76a96156f0
Author: Matthias Clasen <mclasen@redhat.com>
Date:   Tue May 2 06:28:22 2017 -0400

    portal support: Raise the priority for network monitor

    When we are inside a sandbox, we want to use the portal
    implementation, since it is the only one that has a chance
    of working.

(NEWS truncated at 15 lines)